#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/vulture" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d vulture stop || exit $?
        else
		/etc/init.d/vulture stop || exit $?
	fi
fi

#backup models.py for migration
cp -f /var/www/vulture/admin/vulture/models.py /var/www/vulture/admin/vulture/models.py.old
# End automatically added section
